basePath: /api/v1/
info:
  contact: {}
  description: 测试
  license: {}
  title: 测试
  version: 0.0.1
paths:
  /test/{id}:
    get:
      consumes:
      - application/json
      description: 接口详细描述信息
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"RetCode":0,"UserInfo":{},"Action":"GetAllUserResponse"}'
          schema:
            type: string
        "400":
          description: '{"RetCode":0,"UserInfo":{},"Action":"GetAllUserResponse"}'
          schema:
            type: string
      summary: 接口概要说明
      tags:
      - 用户信息
swagger: "2.0"
